# basic options
title: Where Shivam Gandhi Dumps His Thoughts
author: GitHub User
email: shivam (dot) jgandhi (@) gmail.com
description: A wonderful site
twitter_username: 
github_username:  shivamjgandhi

# Build settings
markdown: kramdown
theme: minima
