# basic options
title: Shivam Gandhi's Personal Blog
author: Shivam Gandhi
email: shivam (dot) jgandhi (@) gmail.com
description: This is where I dump my thoughts
twitter_username: 
github_username:  shivamjgandhi

# Build settings
markdown: kramdown
theme: minima
